# Generated by Django 6.0 on 2026-01-12 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.IntegerField(blank=True, null=True)),
                ('original_image', models.ImageField(upload_to='images/original/')),
                ('watermarked_image', models.ImageField(blank=True, null=True, upload_to='images/watermarked/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/thumbnails/')),
                ('capture_time', models.DateTimeField(blank=True, null=True)),
                ('camera_model', models.CharField(blank=True, max_length=100, null=True)),
                ('aperture', models.CharField(blank=True, max_length=100, null=True)),
                ('shutter_speed', models.CharField(blank=True, max_length=100, null=True)),
                ('iso', models.IntegerField(blank=True, null=True)),
                ('focal_length', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('exif', models.JSONField(blank=True, null=True)),
                ('privacy', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PRIVATE', max_length=10)),
                ('view_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('download_count', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
