# Generated by Django 6.0 on 2025-12-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_image_original_image_alter_image_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='original_image',
            field=models.ImageField(upload_to='images/original/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='watermarked_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/watermarked/'),
        ),
    ]
